soc/sdx65: add status for SDX65
linux-msm/mainline-status pull request #35
Opened 2023-07-11 11:29 UTC by RohitAgarwalQUIC

SDX65 is one of the Qualcomm platforms supported by upstream. Describe its status.
Also add the SDX65 entries in the corresponding PMICs present.

2023-07-11 11:35 UTC, lumag requested changes
Generaly looks good, could you please fix several small issues.

2023-07-11 11:35 UTC, lumag commented on _pmic/pm8150b.md
> +This PMIC is usually used with the [SDX65](../soc/sdx65) platform.
.. Or SM8150/SM8250 platforms. Could you please add them too.

2023-07-11 11:35 UTC, lumag commented on _soc/sdx65.md
> +status-cpu-smp:
N/A ?

2023-07-11 11:35 UTC, lumag commented on _soc/sdx65.md
> +status-cpu-llcc:
Probably also N/A? I don't know if SDX65 has LLCC.

2023-07-11 11:35 UTC, lumag commented on _soc/sdx65.md
> +status-dma-gpi:
N/A ? GPI DMA is used on arm64 platforms to provide DMA to QUPv3 I2C  / SPI.

2023-07-11 11:35 UTC, lumag commented on _soc/sdx65.md
> +SDX65 (Olympic)
Is this name public? Well, after this PR it is.

2023-07-12 08:14 UTC, RohitAgarwalQUIC commented on _soc/sdx65.md
> +SDX65 (Olympic)
Yes, Ok.

2023-07-12 08:14 UTC, RohitAgarwalQUIC commented on _soc/sdx65.md
> +status-dma-gpi:
Yes, N/A.

2023-07-12 08:14 UTC, RohitAgarwalQUIC commented on _soc/sdx65.md
> +status-cpu-llcc:
LLCC is actually present on SDX65. But the support is not added yet and also the work is not in progress.

2023-07-12 08:14 UTC, RohitAgarwalQUIC commented on _soc/sdx65.md
> +status-cpu-smp:
Yes. Will put N/A.

2023-07-12 08:14 UTC, RohitAgarwalQUIC commented on _pmic/pm8150b.md
> +This PMIC is usually used with the [SDX65](../soc/sdx65) platform.
Ok Sure.

2023-07-13 12:41 UTC, lumag commented on _soc/sdx65.md
> +status-dma-gpi:
@RohitAgarwalQUIC could you please fix the outstanding issues, then I'll merge this PR.

2023-07-13 12:44 UTC, RohitAgarwalQUIC commented on _soc/sdx65.md
> +status-dma-gpi:
Sure

2023-07-13 12:51 UTC, merged

2023-07-13 12:52 UTC, lumag commented
@RohitAgarwalQUIC thanks!