X1E80100 Updates
linux-msm/mainline-status pull request #64
Opened 2024-08-12 15:25 UTC by abelvesa

Updates for x1e80100 related to BT, GPU and UFS as WIP

2024-08-12 17:28 UTC, lumag commented
Please also run regen.py and commit the results.

2024-08-13 07:57 UTC, abelvesa commented
There are no differences other than the json gem I had to add to the Gemfile in order to get it to work on my side.

2024-08-13 10:57 UTC, lumag commented
@abelvesa you have added entries to soc.yaml. In order for this to work properly you also need to run regen.py, it updates several index scripts.

2024-08-21 04:25 UTC, lumag commented on soc.yaml
> +      name: NVMe
@abelvesa is NVMe support an SoC feature? I don't think we have any special enabling for Qualcomm platforms, do we?
Or, to put things differently, is there anything that stops us from using NVMe on e.g. sm8250 or even msm8996?

2024-10-17 11:56 UTC, lumag commented on _soc/x1e80100.md
> +status-display-dp: WIP
Why is it changed from 6.10 to WIP?

2024-10-17 12:00 UTC, lumag requested changes

2024-10-17 12:00 UTC, lumag commented on _soc/x1e80100.md
> +status-display-gpu: "6.10"
no quotes, please.

2024-10-17 12:00 UTC, lumag commented on _soc/x1e80100.md
> +status-storage-nvme: 6.11
We don't have this status field. Also, what is so important about NVMe? I had this question before, which was left unanswered.

2024-10-17 12:00 UTC, lumag commented on _soc/x1e80100.md
> +status-usb-typec: WIP
Does WIP status concern typec support on the SoC / in dtsi or a particular device combo? In the latter case please use `status-usb-typec-comment` to provide additional details instead of just switching from -next to WIP.

2024-10-21 13:26 UTC, abelvesa commented on _soc/x1e80100.md
> +status-storage-nvme: 6.11
I dropped this new field from the layout but forgot to drop it from the x1e80100 soc as well. Nothing special about nvme. Came to the conclusion after that as long as PCIe is handled correctly, NVMe should just work, therefore no need for dedicated entry for it.

2024-10-21 13:28 UTC, abelvesa commented on _soc/x1e80100.md
> +status-display-dp: WIP
So what does this status mean exactly? Does it mean that as long as the MDSS DPTXx are described correctly, the status should be marked as upstream already? If so, then yes, it should remain unchanged and I'll drop the change.

2024-10-21 13:29 UTC, lumag commented on _soc/x1e80100.md
> +status-storage-nvme: 6.11
SGTM

2024-10-21 13:30 UTC, abelvesa commented on _soc/x1e80100.md
> +status-usb-typec: WIP
Again, what does this status mean? In most cases, type-c needs some kind of sbu mux to have orientation working. At this moment none of the X1E boards have that upstream. The first one that is WIP is CRD with the parade PS8830 retimer.

2024-10-21 16:01 UTC, lumag commented on _soc/x1e80100.md
> +status-usb-typec: WIP
It is for the SoC status. Board support has much more knobs and dependencies. You can still use status-foo-comment field to write additional information. Or you can write everything in the body of the file, below three dashes

2024-10-22 08:21 UTC, lumag approved these changes

2024-10-22 08:21 UTC, merged